apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::761018880324:user/iamadmin
      username: iamadmin
      groups:
        - system:masters
